project_id = "ukwwhwytyovrzefkdeyj"

[functions.automacao-diaria]
verify_jwt = false

[functions.portal-scraper]
verify_jwt = false

[functions.import-licencas]
verify_jwt = false

[functions.gmail-sync-inbox]
verify_jwt = false