/**
 * Conteúdo da aba "API" da página de Ajuda (`src/pages/Ajuda.tsx`), visível apenas para o
 * admin master (`profile.role === 'admin'`). Documenta as duas famílias de rota do sistema:
 *
 * - `ROTAS_FRONTEND`: as telas do React Router, lidas direto de `src/App.tsx`.
 * - `FUNCOES_BORDA`: as funções de borda do Supabase (`supabase/functions/*`), que são a
 *   API real exposta pelo sistema — chamadas em `POST /functions/v1/<nome>`.
 *
 * Escrito à mão, como o conteúdo de Documentação (`ajuda-conteudo.ts`): ao criar rota ou
 * função nova, adicione uma entrada aqui. Não há geração automática — o objetivo é
 * descrição legível, não um espelho mecânico da pasta.
 */

export type AcessoRotaFrontend = 'publica' | 'autenticada' | 'gestor' | 'admin_master';

export interface RotaFrontend {
  caminho: string;
  pagina: string;
  acesso: AcessoRotaFrontend;
  descricao: string;
}

export interface FuncaoBorda {
  /** Nome da pasta em `supabase/functions/`. A rota é `POST /functions/v1/<nome>`. */
  nome: string;
  metodo: string;
  auth: string;
  parametros: string;
  descricao: string;
  resposta: string;
}

export const ROTAS_FRONTEND: RotaFrontend[] = [
  { caminho: '/', pagina: 'Landing', acesso: 'publica', descricao: 'Página de vendas. Quem já tem sessão é levado direto para dentro do sistema.' },
  { caminho: '/login', pagina: 'Login', acesso: 'publica', descricao: 'Entrada por e-mail e senha.' },
  { caminho: '/cadastro', pagina: 'Cadastro', acesso: 'publica', descricao: 'Criação de conta nova (empresa ou vendedor com código de acesso).' },
  { caminho: '/esqueci-senha', pagina: 'EsqueciSenha', acesso: 'publica', descricao: 'Pedido de link de redefinição de senha por e-mail.' },
  { caminho: '/redefinir-senha', pagina: 'RedefinirSenha', acesso: 'publica', descricao: 'Tela que o link de redefinição abre, para escolher a senha nova.' },
  { caminho: '/assinar', pagina: 'Assinar', acesso: 'autenticada', descricao: 'Tela de assinatura/plano. Fora do bloqueio de plano de propósito, para não virar um loop de redirecionamento.' },
  { caminho: '/app', pagina: 'Negocios (pipeline)', acesso: 'autenticada', descricao: 'Home do sistema para quem tem empresa: o funil de negócios (Kanban).' },
  { caminho: '/clientes', pagina: 'Clientes', acesso: 'autenticada', descricao: 'Lista de clientes da empresa.' },
  { caminho: '/clientes/:slug', pagina: 'ClienteDetalhe', acesso: 'autenticada', descricao: 'Ficha de um cliente: contatos, obras, negócios e histórico.' },
  { caminho: '/contatos/:slug', pagina: 'ContatoDetalhe', acesso: 'autenticada', descricao: 'Ficha de um contato dentro de um cliente.' },
  { caminho: '/pedidos', pagina: '— (redireciona para /app)', acesso: 'autenticada', descricao: 'Endereço antigo, mantido só para não quebrar link salvo.' },
  { caminho: '/pedidos/novo', pagina: 'NovoPedido', acesso: 'autenticada', descricao: 'Formulário de negócio (orçamento) novo.' },
  { caminho: '/pedidos/:id/editar', pagina: 'EditarPedido', acesso: 'autenticada', descricao: 'Formulário de edição de um negócio existente.' },
  { caminho: '/obras', pagina: 'Obras', acesso: 'autenticada', descricao: 'Lista de canteiros de obra cadastrados.' },
  { caminho: '/fabricantes', pagina: 'Fabricantes', acesso: 'autenticada', descricao: 'Cadastro das representadas e seus catálogos/tabelas de preço.' },
  { caminho: '/portal', pagina: 'Portal', acesso: 'autenticada', descricao: 'Painel de notícias e licenças (Diário Oficial, obras públicas).' },
  { caminho: '/dashboard', pagina: 'Dashboard', acesso: 'autenticada', descricao: 'Indicadores e gráficos de vendas da empresa.' },
  { caminho: '/hoje', pagina: 'Hoje', acesso: 'autenticada', descricao: 'Pauta do dia: negócios parados e compromissos da agenda.' },
  { caminho: '/calendario', pagina: 'Calendario', acesso: 'autenticada', descricao: 'Agenda de compromissos e prazos.' },
  { caminho: '/tarefas', pagina: 'Tarefas', acesso: 'autenticada', descricao: 'Lista de tarefas da equipe.' },
  { caminho: '/configuracoes', pagina: 'Configuracoes', acesso: 'autenticada', descricao: 'Configurações da empresa, equipe, automação e (para o admin master) da própria conta.' },
  { caminho: '/ajuda', pagina: 'Ajuda', acesso: 'autenticada', descricao: 'Esta página: documentação de uso e, para o admin master, esta aba de API.' },
  { caminho: '/chat', pagina: 'Chat', acesso: 'autenticada', descricao: 'Chat interno da equipe.' },
  { caminho: '/whatsapp', pagina: 'WhatsAppInbox', acesso: 'autenticada', descricao: 'Caixa de entrada do WhatsApp conectado à empresa.' },
  { caminho: '/emails', pagina: 'Emails', acesso: 'autenticada', descricao: 'Caixa de e-mail conectada (Gmail ou IMAP genérico).' },
  { caminho: '/historico', pagina: 'HistoricoAlteracoes', acesso: 'gestor', descricao: 'Histórico de alterações da empresa. Só gestor, dono da empresa ou admin master.' },
  { caminho: '/admin/instancias-whatsapp', pagina: 'AdminWhatsAppInstancias', acesso: 'admin_master', descricao: 'Gestão das instâncias de WhatsApp de todas as empresas. Exclusivo do admin master.' },
  { caminho: '/admin/empresas', pagina: 'AdminEmpresas', acesso: 'admin_master', descricao: 'Painel de todos os assinantes do SaaS: planos, cobrança, usuários. Exclusivo do admin master.' },
  { caminho: '/admin/secoes', pagina: 'AdminSecoes', acesso: 'admin_master', descricao: 'Controle de quais seções cada empresa tem contratadas. Exclusivo do admin master.' },
];

export const FUNCOES_BORDA: FuncaoBorda[] = [
  {
    nome: 'automacao-diaria',
    metodo: 'POST (cron)',
    auth: 'Pública (verify_jwt=false) — usa service_role direto, sem checar quem chama.',
    parametros: 'Nenhum.',
    descricao: 'Rotina diária que gera notificações de follow-up atrasado/do dia e de negócios parados por inatividade.',
    resposta: 'Sucesso 200: { followups_gerados, inatividade_gerados, erros[] }. Erro 500: { error }.',
  },
  {
    nome: 'cobranca-regua',
    metodo: 'POST (cron)',
    auth: 'Requer JWT por padrão, mas roda como service_role — não há checagem de quem chama (rotina de automação).',
    parametros: 'Nenhum.',
    descricao: 'Rotina diária da régua de cobrança: marca/desmarca inadimplência das empresas e envia avisos por e-mail e notificação interna.',
    resposta: 'Sucesso 200: { marcadas, regularizadas, na_regua, avisos_enviados, avisos_ja_enviados, sem_destinatario, prazo_esgotado, falhas[] }. Erro 500 no mesmo formato + { erro }.',
  },
  {
    nome: 'email-callback',
    metodo: 'GET',
    auth: 'Pública (verify_jwt=false) — a autenticidade vem de um `state` de uso único gerado por email-conectar, consumido uma vez só.',
    parametros: 'Query: code, state, error, error_description.',
    descricao: 'Finaliza a conexão OAuth de e-mail (Nylas): troca o código por um grant, garante uma caixa por empresa e grava a conta.',
    resposta: 'Redirect 303 para /emails?conexao=... (não retorna JSON).',
  },
  {
    nome: 'email-conectar',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; papel admin/empresa/gestor; empresa vinculada e não suspensa.',
    parametros: 'Body: { provedor? } (google/microsoft/imap, padrão google).',
    descricao: 'Inicia o fluxo OAuth para conectar a caixa de e-mail da empresa ao Nylas.',
    resposta: 'Sucesso: { url }. Erro: { error, code? } (401/403/404/409/500).',
  },
  {
    nome: 'email-criar-marcador',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; papel admin/empresa/gestor; empresa vinculada e ativa.',
    parametros: 'Body: { nome } (até 100 caracteres).',
    descricao: 'Cria um marcador/pasta na caixa de e-mail conectada da empresa e espelha em email_pastas.',
    resposta: 'Sucesso: { ok: true, pasta: { id, nome } }. Erro: { error } (400/401/403/404/409/502/500).',
  },
  {
    nome: 'email-desconectar',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; papel admin/empresa/gestor.',
    parametros: 'Body opcional: { preservar_mensagens? } (padrão true).',
    descricao: 'Desconecta a caixa de e-mail da empresa, revogando o grant no Nylas e decidindo se preserva o histórico.',
    resposta: 'Sucesso: { ok: true, preservou, mensagens } ou { ok: true, ja_desconectada: true }. Erro: { error }.',
  },
  {
    nome: 'email-enviar',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; exige assinatura ativa da empresa (active/trialing/past_due); acesso à caixa via RLS.',
    parametros: 'Body: { to, subject, body, cc?, bcc?, rascunho_id?, reply_to_message_id?, idempotency_key? }.',
    descricao: 'Envia um e-mail em nome da empresa pela caixa conectada (Nylas), incluindo anexos do rascunho.',
    resposta: 'Sucesso: { ok: true, id, thread_id }. Erro: { error, code? } (400/401/402/403/404/409/413/500/502/504).',
  },
  {
    nome: 'email-marcar-lido',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; acesso a cada mensagem conferido via RLS.',
    parametros: 'Body: { mensagem_id | mensagem_ids[], lido? } (máx. 200 mensagens).',
    descricao: 'Marca uma ou várias mensagens de e-mail como lidas/não lidas e espelha o estado na caixa de origem.',
    resposta: 'Sucesso: { ok: true, lido, alteradas, provedor, enviadas, falhas, detalhe? }. Erro: { error }.',
  },
  {
    nome: 'email-mensagem',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; acesso conferido via RLS (404 uniforme para "não existe" ou "sem acesso").',
    parametros: 'Body: { mensagem_id }.',
    descricao: 'Busca o corpo completo (HTML) e os anexos de uma mensagem de e-mail sob demanda, resolvendo imagens inline.',
    resposta: 'Sucesso: { corpo_html, anexos, cache }. Erro: { error, code? } (400/401/403/404/409/500/502).',
  },
  {
    nome: 'email-mover-marcador',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; acesso conferido via RLS.',
    parametros: 'Body: { pasta_id, mensagem_id | mensagem_ids[] } (máx. 200 mensagens).',
    descricao: 'Move uma ou mais mensagens de e-mail para um marcador de destino, gravando localmente e espelhando no provedor.',
    resposta: 'Sucesso: { ok: true, pasta, alteradas, provedor, movidas, falhas, detalhe? }. Erro: { error }.',
  },
  {
    nome: 'email-sync',
    metodo: 'POST',
    auth: 'Pública (verify_jwt=false) — distingue chamada do cron (Bearer = service role) de chamada de usuário (JWT validado).',
    parametros: 'Body opcional: { limit?, backfill?, pastas? }.',
    descricao: 'Sincroniza mensagens do Nylas para o CRM (novas e atualizadas) e espelha pastas/marcadores.',
    resposta: 'Sucesso: { ok: true, contas, novas, atualizadas, pastas, erros[] }. Erro: { error }.',
  },
  {
    nome: 'email-webhook',
    metodo: 'GET (desafio) / POST (eventos)',
    auth: 'Pública (verify_jwt=false) — valida HMAC-SHA256 no header x-nylas-signature contra NYLAS_WEBHOOK_SECRET.',
    parametros: 'GET: query challenge. POST: payload do Nylas (type, data.object, ...).',
    descricao: 'Recebe notificações do Nylas (novo e-mail, grant revogado etc.) e grava mensagens em email_mensagens.',
    resposta: '{ received: true, ... }. Erro: { error } (400/401/500).',
  },
  {
    nome: 'empresa-excluir',
    metodo: 'POST',
    auth: 'Requer JWT de usuário; exige role === "admin" (admin master).',
    parametros: 'Body: { empresa_id, motivo? }.',
    descricao: 'Encerra uma empresa: cancela a assinatura no Stripe (se houver) e marca a empresa para exclusão via RPC.',
    resposta: 'Sucesso: { ok: true, ...resultado, ...marcacao }. Erro: { error, detalhe? } (400/401/403/500/502).',
  },
  {
    nome: 'eventos-lembrete',
    metodo: 'POST (cron / gatilho do banco)',
    auth: 'Pública (verify_jwt=false) — usa service_role direto, sem checar quem chama.',
    parametros: 'Nenhum.',
    descricao: 'Processa a fila de lembretes de eventos da agenda: gera avisos por sininho, chat interno e e-mail.',
    resposta: 'Sucesso 200: { lembretes_gerados, avisos, concluidos, alertas, erros[] }. Erro 500 no mesmo formato.',
  },
  {
    nome: 'gmail-auth-url',
    metodo: 'POST',
    auth: '🔴 Requer JWT, mas o userId vem direto do corpo sem validar contra o JWT do chamador — falha conhecida, função legada.',
    parametros: 'Body: { userId }.',
    descricao: 'Monta a URL de autorização OAuth do Google (Gmail) para conectar a conta de e-mail pessoal de um usuário.',
    resposta: 'Sucesso: { url }. Erro: { error } (400/500).',
  },
  {
    nome: 'gmail-callback',
    metodo: 'GET',
    auth: 'Pública (verify_jwt=false) — o `state` carrega só o userId, não é um token de uso único.',
    parametros: 'Query: code, state (= userId).',
    descricao: 'Troca o código OAuth do Google por tokens de acesso e salva em gmail_tokens.',
    resposta: 'Redirect 303 para /configuracoes?tab=perfil. Erro 400/500.',
  },
  {
    nome: 'gmail-debug',
    metodo: 'POST',
    auth: 'Requer JWT de usuário, validado via supabaseClient.auth.getUser().',
    parametros: 'Nenhum — usa só o usuário autenticado.',
    descricao: 'Diagnostica a integração Gmail do usuário: token, perfil, mensagens e contagem já sincronizada.',
    resposta: 'Sucesso 200: objeto de diagnóstico. Erro 401/500: { error }.',
  },
  {
    nome: 'gmail-send',
    metodo: 'POST',
    auth: '🔴 Requer JWT, mas usa só o userId do body para buscar tokens, sem confrontar com o JWT do chamador — falha conhecida, função legada.',
    parametros: 'Body: { userId, to, subject, body }.',
    descricao: 'Envia um e-mail via API do Gmail usando os tokens OAuth armazenados do usuário.',
    resposta: 'Sucesso 200: retorno bruto da API do Gmail. Erro: { error } (400/500).',
  },
  {
    nome: 'gmail-sync-inbox',
    metodo: 'POST',
    auth: 'Pública (verify_jwt=false) para a varredura geral (itera todos os usuários); a ação mark_as_read exige JWT.',
    parametros: 'Body: { action?: "mark_as_read", messageId? }, ou vazio para sincronização completa.',
    descricao: 'Sincroniza a caixa de entrada do Gmail (legado, anterior ao Nylas) de todos os usuários conectados.',
    resposta: 'Sucesso: { success: true } ou array { user_id, status, synced? }. Erro: { error }.',
  },
  {
    nome: 'import-data',
    metodo: 'POST',
    auth: 'Requer JWT; confere que empresaId do body bate com a empresa real do usuário. ⚠️ Marcada como código órfão/deprecated no próprio arquivo.',
    parametros: 'Body: { fileContent, importType: "clientes"|"negocios", empresaId }.',
    descricao: 'Usa a API do Gemini para interpretar um arquivo bruto e mapear registros para o schema de clientes ou negócios.',
    resposta: 'Sucesso: { success, inserted, total, errors? }. Erro: { success: false, error } (400/401/403/500).',
  },
  {
    nome: 'import-licencas',
    metodo: 'POST',
    auth: 'Requer JWT; papel gestor/admin/empresa.',
    parametros: 'Body: { rows: LicencaRow[], clear_existing? }.',
    descricao: 'Importa em lote registros de licenças (Extremoz) para a tabela licencas_extremoz.',
    resposta: 'Sucesso: { success: true, inserted, errors, total }. Erro: { success: false, error } (400/401/403/500).',
  },
  {
    nome: 'list-dom-editions',
    metodo: 'POST',
    auth: 'Requer JWT, sem checagem adicional.',
    parametros: 'Body: { mes, ano }.',
    descricao: 'Consulta a API pública do Diário Oficial de Natal e lista as edições em PDF do mês/ano informado.',
    resposta: 'Sucesso: { success: true, edicoes: [...] }. Erro: { success: false, error } (400/500).',
  },
  {
    nome: 'pauta-resumo-diario',
    metodo: 'POST (cron)',
    auth: 'Requer JWT por padrão, mas roda como service_role — sem checagem de quem chama (agendamento diário).',
    parametros: 'Nenhum.',
    descricao: 'Monta e envia por e-mail o resumo diário da pauta de cada usuário (ou o "pulso da equipe" quando a fila pessoal está vazia).',
    resposta: 'Sucesso 200: { destinatarios, enviados, pulsos, pauta_vazia, pulso_vazio, erros[] }. Erro 500: { erro }.',
  },
  {
    nome: 'portal-scraper',
    metodo: 'POST',
    auth: 'Pública (verify_jwt=false) — endpoint público de scraping, sem checagem.',
    parametros: 'Body: { site_id: "idema"|"natal"|"extremoz", search?, year?, month?, max_pdfs? }.',
    descricao: 'Raspa e extrai dados de portais públicos (IDEMA, DOM Natal, DOM Extremoz) — texto, links, tabelas e licenças de PDF.',
    resposta: 'Sucesso: { success: true, site, data: { text, links, table }, meta?, fetched_at }. Erro: { success: false, error, fallback_url? } (400/500/502).',
  },
  {
    nome: 'relay-dom-natal',
    metodo: 'GET',
    auth: 'Requer JWT; restringe o destino a uma allow-list de hosts da Prefeitura de Natal e exige https (proteção contra SSRF).',
    parametros: 'Query: url (endereço de destino no domínio permitido).',
    descricao: 'Repassa uma requisição de rede para o site da Prefeitura de Natal, contornando um bloqueio de firewall do GitHub Actions.',
    resposta: 'Repassa corpo e content-type da resposta de origem. Erro: { error, ... } (400/403/502).',
  },
  {
    nome: 'resolve-pedido-anexo',
    metodo: 'POST',
    auth: 'Requer JWT; confere que empresaId do body bate com a empresa do usuário autenticado.',
    parametros: 'Body: { urls: string[], empresaId } (máx. 50 URLs por chamada).',
    descricao: 'Baixa anexos hospedados na CDN do Bitrix24 (que bloqueia CORS) e reidrata no bucket próprio pedido-anexos.',
    resposta: 'Sucesso: { results: [{ url, falhaDownload }] }. Erro: { error } (400/401/403/500).',
  },
  {
    nome: 'scrape-extremoz-licencas',
    metodo: 'POST',
    auth: 'Dois caminhos: chamada de serviço (service_role, do pg_cron, sem checagem extra) ou usuário exigindo a seção "portal" contratada.',
    parametros: 'Body opcional: { ano?, anos?[] }.',
    descricao: 'Raspa o Diário Oficial de Extremoz, extrai publicações de licença (LP/LI/LO) de PDFs novos e grava em licencas_extremoz.',
    resposta: 'Sucesso: { success: true, novas, processados, inseridos, restantes, parcial }. Erro: { success: false, error } (401/403/500).',
  },
  {
    nome: 'scrape-licencas-idema',
    metodo: 'POST',
    auth: 'Mesmo esquema de dois caminhos: service_role do pg_cron ou usuário exigindo a seção "portal" contratada.',
    parametros: 'Body opcional: { data_inicial?, data_final? } (ISO).',
    descricao: 'Raspa o portal do IDEMA por licenças emitidas (LP/LI/LO), grava/atualiza em licencas_idema e extrai dados do PDF de cada uma.',
    resposta: 'Sucesso: { inseridos, total_scraped, pdf_novos, por_tipo, licencas[] }. Erro: { error, inseridos: 0, ... } (500).',
  },
  {
    nome: 'stripe-checkout',
    metodo: 'POST',
    auth: 'Requer JWT; papel admin/empresa/gestor, ou ser dono (owner_id) da empresa.',
    parametros: 'Body: { plano? } (slug do plano, padrão "lancamento").',
    descricao: 'Cria uma sessão de Checkout do Stripe para a empresa contratar um plano.',
    resposta: 'Sucesso: { url }. Erro: { error, code? } (400/401/403/404/409/500).',
  },
  {
    nome: 'stripe-portal',
    metodo: 'POST',
    auth: 'Requer JWT; papel admin/empresa/gestor, ou ser dono da empresa.',
    parametros: 'Nenhum.',
    descricao: 'Abre uma sessão do Portal de Cobrança do Stripe para a empresa gerenciar a própria assinatura.',
    resposta: 'Sucesso: { url }. Erro: { error, code? } (401/403/404/409/500).',
  },
  {
    nome: 'stripe-webhook',
    metodo: 'POST',
    auth: 'Pública (verify_jwt=false) — valida a assinatura stripe-signature contra STRIPE_WEBHOOK_SECRET; deduplica por id do evento.',
    parametros: 'Corpo cru = payload de evento do Stripe. Header: stripe-signature.',
    descricao: 'Processa eventos de assinatura do Stripe e atualiza o estado de assinatura da empresa.',
    resposta: '{ received: true, ... }. Erro: { error } (400/500).',
  },
  {
    nome: 'whatsapp-admin-provision',
    metodo: 'POST',
    auth: 'Requer JWT; papel admin/empresa/gestor; confere que os alvos pertencem à mesma empresa (exceto admin master).',
    parametros: 'Body: { action: "create"|"link"|"unlink"|"delete", instance_id?, target_usuario_id?, target_usuario_ids?[] }.',
    descricao: 'Administra instâncias WhatsApp (uazapi) de uma empresa: cria, vincula/desvincula usuários e exclui instâncias.',
    resposta: 'Sucesso: { success: true, ... }. Erro: { error, detail? } (400/403/404/500).',
  },
  {
    nome: 'whatsapp-contact-photo',
    metodo: 'POST',
    auth: 'Requer JWT; confere que a conversa pertence à mesma empresa (404 em vez de 403).',
    parametros: 'Body: { conversa_id }.',
    descricao: 'Busca e cacheia a foto de perfil de um contato do WhatsApp via uazapi.',
    resposta: 'Sucesso: { foto_perfil_url, foto_perfil_expires_at }. Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-contact-rename',
    metodo: 'POST',
    auth: 'Requer JWT; confere que a conversa pertence à empresa do usuário (404 em vez de 403).',
    parametros: 'Body: { conversa_id, nome }.',
    descricao: 'Renomeia o contato de uma conversa do WhatsApp — na agenda real (contatos) ou só localmente (grupos).',
    resposta: 'Sucesso: { nome_contato, synced_to_whatsapp }. Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-delete-message',
    metodo: 'POST',
    auth: 'Requer JWT; filtra a mensagem por empresa_id do chamador.',
    parametros: 'Body: { mensagemId }.',
    descricao: 'Apaga uma mensagem de WhatsApp para todos os participantes via uazapi e marca como apagada no CRM.',
    resposta: 'Sucesso: { ok: true }. Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-edit-message',
    metodo: 'POST',
    auth: 'Requer JWT; filtra por empresa_id; exige mensagem de saída, tipo texto, não apagada, dentro da janela de 15 min.',
    parametros: 'Body: { mensagemId, novoTexto }.',
    descricao: 'Edita o texto de uma mensagem de WhatsApp já enviada, dentro da janela permitida pela operadora.',
    resposta: 'Sucesso: { ok: true } (ou { ok: true, semMudanca: true }). Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-group-create',
    metodo: 'POST',
    auth: 'Requer JWT; exige instância WhatsApp vinculada e conectada.',
    parametros: 'Body: { nome, participantes: string[] }.',
    descricao: 'Cria um novo grupo no WhatsApp via uazapi e registra a conversa no CRM, atribuindo o criador como responsável.',
    resposta: 'Sucesso: { ok: true, conversa }. Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-group-participants',
    metodo: 'POST',
    auth: 'Requer JWT; confere que a conversa pertence à empresa do usuário (404 em vez de 403).',
    parametros: 'Body: { conversa_id }.',
    descricao: 'Lista os participantes de um grupo do WhatsApp (nome e telefone), cruzado com a agenda de contatos.',
    resposta: 'Sucesso: { participantes: [...] }. Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-participant-photo',
    metodo: 'POST',
    auth: 'Requer JWT.',
    parametros: 'Body: { telefone }.',
    descricao: 'Busca e cacheia a foto de perfil de um participante/telefone específico do WhatsApp (útil para membros de grupo).',
    resposta: 'Sucesso: { foto_perfil_url }. Erro: { error, detail? } (400/401/404/500/502).',
  },
  {
    nome: 'whatsapp-provision',
    metodo: 'POST',
    auth: 'Requer JWT; para provisionar/excluir instância de outro usuário exige papel admin/empresa/gestor e mesma empresa.',
    parametros: 'Body: { action?: "delete", target_usuario_id? } (sem body = auto-provisionamento do próprio usuário).',
    descricao: 'Provisiona ou remove a instância de WhatsApp (uazapi) do próprio usuário ou de um colega.',
    resposta: 'Sucesso: { success: true, instanceName, alreadyProvisioned?, reused? }. Erro: { error, detail? } (403/404/500).',
  },
  {
    nome: 'whatsapp-send',
    metodo: 'POST',
    auth: 'Pública (verify_jwt=false) — a própria função confere a sessão no corpo; confere empresa da conversa e vínculo do remetente com a instância.',
    parametros: 'Body: { telefone, mensagem?, conversa_id?, tipo?, media_url?, media_mime?, nome_arquivo?, ptt?, media_hash?, mentions?, quoted_wamid?, ... }.',
    descricao: 'Envia uma mensagem de WhatsApp (texto, mídia, contato ou figurinha) pela instância uazapi vinculada.',
    resposta: 'Sucesso: { ok: true, wamid, conversa_id, aviso? }. Erro: { error, detail?, code? } (400/401/403/404/500/502).',
  },
  {
    nome: 'whatsapp-send-reaction',
    metodo: 'POST',
    auth: 'Requer JWT; exige instância vinculada e conectada.',
    parametros: 'Body: { wamid, emoji? }.',
    descricao: 'Envia (ou remove, com emoji vazio) uma reação de emoji a uma mensagem de WhatsApp existente.',
    resposta: 'Sucesso: { ok: true }. Erro: { error, detail? } (400/500/502).',
  },
  {
    nome: 'whatsapp-webhook',
    metodo: 'POST',
    auth: 'Pública (verify_jwt=false). Há checagem de x-webhook-secret, mas roda hoje em MODO OBSERVAÇÃO — não recusa chamada nenhuma ainda.',
    parametros: 'Query: instance (ou header x-instance-name). Corpo: payload de evento da uazapi.',
    descricao: 'Recebe todos os eventos da instância WhatsApp (mensagens, status, conexão, chamadas), grava no CRM e sinaliza conversas sem responsável.',
    resposta: '{ ok: true } (mesmo em eventos ignorados). Erro: { error } (400/404/500).',
  },
];
